import argparse
import json
from pathlib import Path

STUB_HEADER = "// AUTO-GENERATED STUB\n// Generated by Circle OS scaffold suite.\n\n"

TS_STUB = STUB_HEADER + "export const placeholder = true\n"
TSX_STUB = STUB_HEADER + "export default function Placeholder() {\n  return null\n}\n"
PY_STUB = '''"""AUTO-GENERATED STUB.\nGenerated by Circle OS scaffold suite.\n"""\n\ndef main() -> None:\n    print("stub")\n\nif __name__ == "__main__":\n    main()\n'''

def ensure_file(path: Path, force: bool = False) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        return f"Exists: {path}"
    if path.suffix == ".tsx":
        content = TSX_STUB
    elif path.suffix == ".ts":
        content = TS_STUB
    elif path.suffix == ".py":
        content = PY_STUB
    else:
        content = STUB_HEADER
    path.write_text(content, encoding="utf-8")
    return f"Created: {path}"

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--build-map", required=True)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    build_map_path = Path(args.build_map).resolve()
    build_map = json.loads(build_map_path.read_text(encoding="utf-8"))
    root = repo_root / build_map["root"]

    for folder, files in build_map.get("shared", {}).items():
        for file_name in files:
            print(ensure_file(root / folder / file_name, force=args.force))

    for _, sections in build_map.get("circles", {}).items():
        for folder, files in sections.items():
            for file_name in files:
                print(ensure_file(root / folder / file_name, force=args.force))

if __name__ == "__main__":
    main()
