import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "app" / "src"

MODULES = APP / "modules"
CARDS = APP / "cards"
SERVICES = APP / "shared" / "utils" / "db"
PLATFORM = APP / "platform"

def list_files(path):
    results = []
    if not path.exists():
        return results
    for root, dirs, files in os.walk(path):
        for f in files:
            results.append(os.path.relpath(os.path.join(root,f),ROOT))
    return sorted(results)

def write_section(file, title, items):
    file.write(f"\n\n## {title}\n\n")
    if not items:
        file.write("_none_\n")
        return
    for i in items:
        file.write(f"- {i}\n")

def main():

    report_path = ROOT / "analysis" / "platform_system_map.md"
    report_path.parent.mkdir(exist_ok=True)

    modules = list_files(MODULES)
    cards = list_files(CARDS)
    services = list_files(SERVICES)
    platform = list_files(PLATFORM)

    with open(report_path,"w",encoding="utf-8") as f:

        f.write("# Platform System Map\n")
        f.write("\nGenerated by platform_mapper.py\n")

        write_section(f,"Modules",modules)
        write_section(f,"Cards",cards)
        write_section(f,"Services",services)
        write_section(f,"Platform Kernel",platform)

    print("Platform map generated:")
    print(report_path)

if __name__ == "__main__":
    main()
